/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BaliAtvAdventureRouteImport } from './routes/bali-atv-adventure'
import { Route as BaliBuggyAdventureRouteImport } from './routes/bali-buggy-adventure'
import { Route as BaliJeepSunriseRouteImport } from './routes/bali-jeep-sunrise'
import { Route as BaliPrivateToursRouteImport } from './routes/bali-private-tours'
import { Route as BaliSafariMarineParkRouteImport } from './routes/bali-safari-marine-park'
import { Route as BaliSwingRouteImport } from './routes/bali-swing'
import { Route as BaliZooRouteImport } from './routes/bali-zoo'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as NusaPenidaToursRouteImport } from './routes/nusa-penida-tours'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BaliAtvAdventureRoute = BaliAtvAdventureRouteImport.update({
  id: '/bali-atv-adventure',
  path: '/bali-atv-adventure',
  getParentRoute: () => rootRouteImport,
} as any)
const BaliBuggyAdventureRoute = BaliBuggyAdventureRouteImport.update({
  id: '/bali-buggy-adventure',
  path: '/bali-buggy-adventure',
  getParentRoute: () => rootRouteImport,
} as any)
const BaliJeepSunriseRoute = BaliJeepSunriseRouteImport.update({
  id: '/bali-jeep-sunrise',
  path: '/bali-jeep-sunrise',
  getParentRoute: () => rootRouteImport,
} as any)
const BaliPrivateToursRoute = BaliPrivateToursRouteImport.update({
  id: '/bali-private-tours',
  path: '/bali-private-tours',
  getParentRoute: () => rootRouteImport,
} as any)
const BaliSafariMarineParkRoute = BaliSafariMarineParkRouteImport.update({
  id: '/bali-safari-marine-park',
  path: '/bali-safari-marine-park',
  getParentRoute: () => rootRouteImport,
} as any)
const BaliSwingRoute = BaliSwingRouteImport.update({
  id: '/bali-swing',
  path: '/bali-swing',
  getParentRoute: () => rootRouteImport,
} as any)
const BaliZooRoute = BaliZooRouteImport.update({
  id: '/bali-zoo',
  path: '/bali-zoo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const NusaPenidaToursRoute = NusaPenidaToursRouteImport.update({
  id: '/nusa-penida-tours',
  path: '/nusa-penida-tours',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bali-atv-adventure': typeof BaliAtvAdventureRoute
  '/bali-buggy-adventure': typeof BaliBuggyAdventureRoute
  '/bali-jeep-sunrise': typeof BaliJeepSunriseRoute
  '/bali-private-tours': typeof BaliPrivateToursRoute
  '/bali-safari-marine-park': typeof BaliSafariMarineParkRoute
  '/bali-swing': typeof BaliSwingRoute
  '/bali-zoo': typeof BaliZooRoute
  '/contact': typeof ContactRoute
  '/experiences': typeof ExperiencesRoute
  '/nusa-penida-tours': typeof NusaPenidaToursRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bali-atv-adventure': typeof BaliAtvAdventureRoute
  '/bali-buggy-adventure': typeof BaliBuggyAdventureRoute
  '/bali-jeep-sunrise': typeof BaliJeepSunriseRoute
  '/bali-private-tours': typeof BaliPrivateToursRoute
  '/bali-safari-marine-park': typeof BaliSafariMarineParkRoute
  '/bali-swing': typeof BaliSwingRoute
  '/bali-zoo': typeof BaliZooRoute
  '/contact': typeof ContactRoute
  '/experiences': typeof ExperiencesRoute
  '/nusa-penida-tours': typeof NusaPenidaToursRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bali-atv-adventure': typeof BaliAtvAdventureRoute
  '/bali-buggy-adventure': typeof BaliBuggyAdventureRoute
  '/bali-jeep-sunrise': typeof BaliJeepSunriseRoute
  '/bali-private-tours': typeof BaliPrivateToursRoute
  '/bali-safari-marine-park': typeof BaliSafariMarineParkRoute
  '/bali-swing': typeof BaliSwingRoute
  '/bali-zoo': typeof BaliZooRoute
  '/contact': typeof ContactRoute
  '/experiences': typeof ExperiencesRoute
  '/nusa-penida-tours': typeof NusaPenidaToursRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bali-atv-adventure'
    | '/bali-buggy-adventure'
    | '/bali-jeep-sunrise'
    | '/bali-private-tours'
    | '/bali-safari-marine-park'
    | '/bali-swing'
    | '/bali-zoo'
    | '/contact'
    | '/experiences'
    | '/nusa-penida-tours'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bali-atv-adventure'
    | '/bali-buggy-adventure'
    | '/bali-jeep-sunrise'
    | '/bali-private-tours'
    | '/bali-safari-marine-park'
    | '/bali-swing'
    | '/bali-zoo'
    | '/contact'
    | '/experiences'
    | '/nusa-penida-tours'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bali-atv-adventure'
    | '/bali-buggy-adventure'
    | '/bali-jeep-sunrise'
    | '/bali-private-tours'
    | '/bali-safari-marine-park'
    | '/bali-swing'
    | '/bali-zoo'
    | '/contact'
    | '/experiences'
    | '/nusa-penida-tours'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BaliAtvAdventureRoute: typeof BaliAtvAdventureRoute
  BaliBuggyAdventureRoute: typeof BaliBuggyAdventureRoute
  BaliJeepSunriseRoute: typeof BaliJeepSunriseRoute
  BaliPrivateToursRoute: typeof BaliPrivateToursRoute
  BaliSafariMarineParkRoute: typeof BaliSafariMarineParkRoute
  BaliSwingRoute: typeof BaliSwingRoute
  BaliZooRoute: typeof BaliZooRoute
  ContactRoute: typeof ContactRoute
  ExperiencesRoute: typeof ExperiencesRoute
  NusaPenidaToursRoute: typeof NusaPenidaToursRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bali-atv-adventure': {
      id: '/bali-atv-adventure'
      path: '/bali-atv-adventure'
      fullPath: '/bali-atv-adventure'
      preLoaderRoute: typeof BaliAtvAdventureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bali-buggy-adventure': {
      id: '/bali-buggy-adventure'
      path: '/bali-buggy-adventure'
      fullPath: '/bali-buggy-adventure'
      preLoaderRoute: typeof BaliBuggyAdventureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bali-jeep-sunrise': {
      id: '/bali-jeep-sunrise'
      path: '/bali-jeep-sunrise'
      fullPath: '/bali-jeep-sunrise'
      preLoaderRoute: typeof BaliJeepSunriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bali-private-tours': {
      id: '/bali-private-tours'
      path: '/bali-private-tours'
      fullPath: '/bali-private-tours'
      preLoaderRoute: typeof BaliPrivateToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bali-safari-marine-park': {
      id: '/bali-safari-marine-park'
      path: '/bali-safari-marine-park'
      fullPath: '/bali-safari-marine-park'
      preLoaderRoute: typeof BaliSafariMarineParkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bali-swing': {
      id: '/bali-swing'
      path: '/bali-swing'
      fullPath: '/bali-swing'
      preLoaderRoute: typeof BaliSwingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bali-zoo': {
      id: '/bali-zoo'
      path: '/bali-zoo'
      fullPath: '/bali-zoo'
      preLoaderRoute: typeof BaliZooRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nusa-penida-tours': {
      id: '/nusa-penida-tours'
      path: '/nusa-penida-tours'
      fullPath: '/nusa-penida-tours'
      preLoaderRoute: typeof NusaPenidaToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BaliAtvAdventureRoute: BaliAtvAdventureRoute,
  BaliBuggyAdventureRoute: BaliBuggyAdventureRoute,
  BaliJeepSunriseRoute: BaliJeepSunriseRoute,
  BaliPrivateToursRoute: BaliPrivateToursRoute,
  BaliSafariMarineParkRoute: BaliSafariMarineParkRoute,
  BaliSwingRoute: BaliSwingRoute,
  BaliZooRoute: BaliZooRoute,
  ContactRoute: ContactRoute,
  ExperiencesRoute: ExperiencesRoute,
  NusaPenidaToursRoute: NusaPenidaToursRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
